argument_specs:
  main:
    short_description: installs PiHole within docker
    description: a role for installing PiHole as a docker container with the help of compose
    author:
      - Nils Ost (@nils-ost)
    version_added: 1.0.0
    options:
      pihole_compose_dir:
        type: "str"
        required: false
        default: /opt/pihole
      pihole_auto_upgrade:
        type: "bool"
        required: false
        default: false
      pihole_port:
        type: "int"
        required: false
        default: 80
      pihole_timezone:
        type: "str"
        required: false
        default: "Europe/Berlin"
      pihole_api_password:
        type: "str"
        required: false
        default: secret
